PACKAGE = ecommerce_worker
PYTHON_VERSION = py35

help: ## display this help message
	@echo "Please use \`make <target>' where <target> is one of"
	@grep '^[a-zA-Z]' $(MAKEFILE_LIST) | sort | awk -F ':.*?## ' 'NF==2 {printf "\033[36m  %-25s\033[0m %s\n", $$1, $$2}'

requirements:  ## install requirements for local development
	pip3 install -r requirements/test.txt

requirements_tox:  ## install tox requirements
	pip3 install -r requirements/tox.txt

worker: ## start the Celery worker process
	celery -A ecommerce_worker worker --app=$(PACKAGE).celery_app:app --loglevel=info --queue=fulfillment,email_marketing

test: requirements_tox  ## run unit tests and report on coverage
	tox -e ${PYTHON_VERSION}

quality: requirements_tox  ## run pep8 and pylint
	tox -e quality

validate: clean test quality  ## run tests and quality checks

clean:  ## delete generated byte code and coverage reports
	find . -name '*.pyc' -delete
	coverage erase
	rm -rf cover htmlcov

export CUSTOM_COMPILE_COMMAND = make upgrade
upgrade:  ## update the requirements/*.txt files with the latest packages satisfying requirements/*.in
	pip3 install -q -r requirements/pip_tools.txt
	pip-compile --rebuild --upgrade -o requirements/pip_tools.txt requirements/pip_tools.in
	pip-compile --upgrade -o requirements/tox.txt requirements/tox.in
	pip-compile --upgrade -o requirements/base.txt requirements/base.in
	pip-compile --upgrade -o requirements/test.txt requirements/test.in
	pip-compile --upgrade -o requirements/optional.txt requirements/optional.in
	pip-compile --upgrade -o requirements/production.txt requirements/production.in
	# Let tox control the Django version for tests
	sed '/^[dD]jango==/d' requirements/test.txt > requirements/test.tmp
	mv requirements/test.tmp requirements/test.txt

.PHONY: help requirements worker test html_coverage quality validate clean upgrade
