PACKAGE = ecommerce_worker
PYTHON_VERSION = py27

help:
	@echo '                                                                                             '
	@echo 'Makefile for the edX ecommerce worker project.                                               '
	@echo '                                                                                             '
	@echo 'Usage:                                                                                       '
	@echo '    make help                         display this message                                   '
	@echo '    make requirements                 install requirements for local development             '
	@echo '    make worker                       start the Celery worker process                        '
	@echo '    make test                         run unit tests and report on coverage                  '
	@echo '    make html_coverage                generate and view HTML coverage report                 '
	@echo '    make quality                      run pep8 and pylint                                    '
	@echo '    make validate                     run tests and quality checks                           '
	@echo '    make clean                        delete generated byte code and coverage reports        '
	@echo '                                                                                             '

requirements:
	pip install -r requirements/local.txt

requirements_tox:
	pip install -r requirements/tox.txt

worker:
	celery -A ecommerce_worker worker --app=$(PACKAGE).celery_app:app --loglevel=info --queue=fulfillment,email_marketing

test: requirements_tox
	tox -e ${PYTHON_VERSION}

quality: requirements_tox
	tox -e quality

validate: clean test quality

clean:
	find . -name '*.pyc' -delete
	coverage erase
	rm -rf cover htmlcov

upgrade: export CUSTOM_COMPILE_COMMAND=make upgrade
upgrade: ## update the requirements/*.txt files with the latest packages satisfying requirements/*.in
	pip install -r requirements/pip-tools.txt
	pip-compile --rebuild --upgrade -o requirements/pip-tools.txt requirements/pip-tools.in
	pip-compile --rebuild --upgrade -o requirements/base.txt requirements/base.in requirements/app.in
	pip-compile --rebuild --upgrade -o requirements/tox.txt requirements/tox.in
	pip-compile --rebuild --upgrade -o requirements/test.txt requirements/test.in
	pip-compile --rebuild --upgrade -o requirements/optional.txt requirements/optional.in
	pip-compile --rebuild --upgrade -o requirements/local.txt requirements/local.in
	pip-compile --rebuild --upgrade -o requirements/production.txt requirements/production.in

.PHONY: help requirements worker test html_coverage quality validate clean
